# Generated by Django 5.0.7 on 2024-07-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_uk', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
